GET http://localhost:3000/

###

POST http://localhost:3000/create
Content-Type: application/json 

{
    "id": "89347893",
    "username": "Callan",
    "password": "Password"
}

###

GET http://localhost:3000/users


###

GET http://localhost:3000/viewProducts

###

GET http://localhost:3000/api/products

## Heroku GET Requests ##

GET http://coffee-co.herokuapp.com

###

GET http://coffee-co.herokuapp.com/api/products

###

GET http://coffee-co.herokuapp.com/api/users