###########################
### Local Host REQUESTS ###
###########################

GET http://localhost:3000/

###

POST http://localhost:3000/create
Content-Type: application/json 

{
    "id": "89347893",
    "username": "Callan",
    "password": "Password"
}

###

GET http://localhost:3000/users

###

GET http://localhost:3000/viewProducts

###

GET http://localhost:3000/api/products

###########################
##### HEROKU REQUESTS #####
###########################

GET http://coffee-co.herokuapp.com

###

GET http://coffee-co.herokuapp.com/api/products

###

GET http://coffee-co.herokuapp.com/api/users

###

POST http://coffee-co.herokuapp.com/api/products
Content-Type: application/json 

{
    "name": "Test Product",
    "price": "10",
    "description": "This is a POST Request"
}

###

POST http://coffee-co.herokuapp.com/api/users/login 
Content-Type: application/json 

{
    "username": "admin",
    "password": "admin"
}

###

POST http://coffee-co.herokuapp.com/api/users/
Content-Type: application/json 

{
    "username": "New User",
    "password": "Password",
    "isAdmin": false
}